# Where we'll write the CSV files from Google Sheets.
#
# You'll add these CSVs to the Git repository, and we'll generate pages from
# the CSV data. When journalists edit and publish the Google Sheet, that
# won't affect the repository until a developer refreshes it.
#
# If the code path is "app/sheets" and the slug is "index", the syntax tree will
# go in "app/sheets/index.csv".
code_path: app/google-sheets

sheets:
  # Put Google Sheets documents here. They must be published to the public and
  # their URLs must end with "?format=csv".
