index:
  path: _root
  model: index

'':
  path: ''
  redirect: index

# HACK: for share-page and share-image, we don't actually render all the tokens
# each time we run ./serve.js -- that would take way too long. Instead, we
# _pretend_ these are all being generated: we call
# `PageContext.prototype.path_to(token)` as if they were.
share-page:
  path: :token
  collection: tokens

# HACK: "methodology" is a regular token, so it has a regular share page.
# However, we want to put special text and meta on the "methodology" page
# instead of presenting the regular search interface. So we put it _after_
# `share-page` in this config file, and it will overwrite it.
methodology:
  model: methodology

share-image:
  path: share/:token.jpg
  collection: tokens
  blob: image
  content-type: image/jpeg

test-social-images:
  model: tokens
